name: Detect Language and Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-language:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Detect Programming Language
        run: |
          FILES=$(ls)
          if ls *.py >/dev/null 2>&1; then
            echo "Language detected: Python"
            echo "LANGUAGE=python" >> $GITHUB_ENV
          elif ls *.php >/dev/null 2>&1; then
            echo "Language detected: PHP"
            echo "LANGUAGE=php" >> $GITHUB_ENV
          elif ls *.js >/dev/null 2>&1; then
            echo "Language detected: JavaScript"
            echo "LANGUAGE=javascript" >> $GITHUB_ENV
          else
            echo "Language not detected"
            exit 1
          fi

      - name: Run Tests for Detected Language
        run: |
          if [ "$LANGUAGE" == "python" ]; then
            echo "Running Python Tests..."
            python -m unittest discover || echo "No tests found"
          elif [ "$LANGUAGE" == "php" ]; then
            echo "Running PHP Tests..."
            php -l . || echo "Syntax check failed"
          elif [ "$LANGUAGE" == "javascript" ]; then
            echo "Running JavaScript Tests..."
            npm install && npm test || echo "No tests found"
          else
            echo "No valid language detected"
            exit 1
          fi
